Repository mercadolibre/fury_andesui-ios, pull requests merged in 2020-04, with the labels that each got.

#37 AndesBadge (just Pill)
  CHANGELOG.md
  Example/AndesUI.xcodeproj/project.pbxproj
  Example/AndesUI/AndesUI-demoapp-Bridging-Header.h
  Example/AndesUI/Badges/BadgesRouter.swift
  Example/AndesUI/Badges/Views/AndesBadgeShowcaseViewController.swift
  Example/AndesUI/Badges/Views/AndesBadgeShowcaseViewController.xib
  Example/AndesUI/Badges/Views/BadgeObjCViewController.h
  Example/AndesUI/Badges/Views/BadgeObjCViewController.m
  Example/AndesUI/Badges/Views/BadgeObjCViewController.xib
  Example/AndesUI/Badges/Views/BadgeViewController.swift
  Example/AndesUI/Badges/Views/BadgeViewController.xib
  Example/AndesUI/Base.lproj/LaunchScreen.xib
  Example/AndesUI/Home/Presenters/HomePresenter.swift
  Example/AndesUI/Home/Routers/HomeRouter.swift
  Example/AndesUI/Home/Views/HomeViewController.swift
  Example/AndesUI/Home/Views/HomeViewController.xib
  Example/AndesUI/Localizable.strings
  Example/Tests/AndesBadgeTests.swift
  LibraryComponents/Classes/AndesBadge/AndesBadge.swift
  LibraryComponents/Classes/AndesBadge/Border/AndesBadgeBorder.swift
  LibraryComponents/Classes/AndesBadge/Border/AndesBadgeBorderCorner.swift
  LibraryComponents/Classes/AndesBadge/Border/AndesBadgeBorderFactory.swift
  LibraryComponents/Classes/AndesBadge/Border/AndesBadgeBorderProtocol.swift
  LibraryComponents/Classes/AndesBadge/Border/AndesBadgeBorderRounded.swift
  LibraryComponents/Classes/AndesBadge/Border/AndesBadgeBorderStandard.swift
  LibraryComponents/Classes/AndesBadge/Config/AndesBadgeViewConfig.swift
  LibraryComponents/Classes/AndesBadge/Config/AndesBadgeViewConfigFactory.swift
  LibraryComponents/Classes/AndesBadge/Hierarchy/AndesBadgeHierarchy.swift
  LibraryComponents/Classes/AndesBadge/Hierarchy/AndesBadgeHierarchyFactory.swift
  LibraryComponents/Classes/AndesBadge/Hierarchy/AndesBadgeHierarchyLoud.swift
  LibraryComponents/Classes/AndesBadge/Hierarchy/AndesBadgeHierarchyProtocol.swift
  LibraryComponents/Classes/AndesBadge/Hierarchy/AndesBadgeHierarchyQuiet.swift
  LibraryComponents/Classes/AndesBadge/Modifier/AndesBadgeModifier.swift
  LibraryComponents/Classes/AndesBadge/Size/AndesBadgeSize.swift
  LibraryComponents/Classes/AndesBadge/Size/AndesBadgeSizeFactory.swift
  LibraryComponents/Classes/AndesBadge/Size/AndesBadgeSizeLarge.swift
  LibraryComponents/Classes/AndesBadge/Size/AndesBadgeSizeProtocol.swift
  LibraryComponents/Classes/AndesBadge/Size/AndesBadgeSizeSmall.swift
  LibraryComponents/Classes/AndesBadge/Type/AndesBadgeType.swift
  LibraryComponents/Classes/AndesBadge/Type/AndesBadgeTypeError.swift
  LibraryComponents/Classes/AndesBadge/Type/AndesBadgeTypeFactory.swift
  LibraryComponents/Classes/AndesBadge/Type/AndesBadgeTypeHighlight.swift
  LibraryComponents/Classes/AndesBadge/Type/AndesBadgeTypeNeutral.swift
  LibraryComponents/Classes/AndesBadge/Type/AndesBadgeTypeProtocol.swift
  LibraryComponents/Classes/AndesBadge/Type/AndesBadgeTypeSuccess.swift
  LibraryComponents/Classes/AndesBadge/Type/AndesBadgeTypeWarning.swift
  LibraryComponents/Classes/AndesBadge/View/AndesBadgeAbstractView.swift
  LibraryComponents/Classes/AndesBadge/View/AndesBadgeView.swift
  LibraryComponents/Classes/AndesBadge/View/Pill/AndesBadgeViewPill.swift
  LibraryComponents/Classes/AndesBadge/View/Pill/AndesBadgeViewPill.xib
Labels: New Component

#49 Credits icons
  CHANGELOG.md
  LibraryComponents/Assets/Images.xcassets/andes_otros_almanaque_20.imageset/Contents.json
  LibraryComponents/Assets/Images.xcassets/andes_otros_almanaque_20.imageset/andes_otros_almanaque_20-1.png
  LibraryComponents/Assets/Images.xcassets/andes_otros_almanaque_20.imageset/andes_otros_almanaque_20-2.png
  LibraryComponents/Assets/Images.xcassets/andes_otros_almanaque_20.imageset/andes_otros_almanaque_20.png
  LibraryComponents/Assets/Images.xcassets/andes_otros_almanaque_24.imageset/Contents.json
  LibraryComponents/Assets/Images.xcassets/andes_otros_almanaque_24.imageset/andes_otros_almanaque_24-1.png
  LibraryComponents/Assets/Images.xcassets/andes_otros_almanaque_24.imageset/andes_otros_almanaque_24-2.png
  LibraryComponents/Assets/Images.xcassets/andes_otros_almanaque_24.imageset/andes_otros_almanaque_24.png
  LibraryComponents/Assets/Images.xcassets/andes_pagar_y_cobrar_efectivo_24.imageset/Contents.json
  LibraryComponents/Assets/Images.xcassets/andes_pagar_y_cobrar_efectivo_24.imageset/andes_pagar_y_cobrar_efectivo_24-1.png
  LibraryComponents/Assets/Images.xcassets/andes_pagar_y_cobrar_efectivo_24.imageset/andes_pagar_y_cobrar_efectivo_24-2.png
  LibraryComponents/Assets/Images.xcassets/andes_pagar_y_cobrar_efectivo_24.imageset/andes_pagar_y_cobrar_efectivo_24.png
  LibraryComponents/Assets/Images.xcassets/andes_pagar_y_cobrar_facturacion_24.imageset/Contents.json
  LibraryComponents/Assets/Images.xcassets/andes_pagar_y_cobrar_facturacion_24.imageset/andes_pagar_y_cobrar_facturacion_24-1.png
  LibraryComponents/Assets/Images.xcassets/andes_pagar_y_cobrar_facturacion_24.imageset/andes_pagar_y_cobrar_facturacion_24-2.png
  LibraryComponents/Assets/Images.xcassets/andes_pagar_y_cobrar_facturacion_24.imageset/andes_pagar_y_cobrar_facturacion_24.png
  LibraryComponents/Assets/Images.xcassets/andes_pagar_y_cobrar_tarjeta_de_credito_24.imageset/Contents.json
  LibraryComponents/Assets/Images.xcassets/andes_pagar_y_cobrar_tarjeta_de_credito_24.imageset/andes_pagar_y_cobrar_tarjeta_de_credito_24-1.png
  LibraryComponents/Assets/Images.xcassets/andes_pagar_y_cobrar_tarjeta_de_credito_24.imageset/andes_pagar_y_cobrar_tarjeta_de_credito_24-2.png
  LibraryComponents/Assets/Images.xcassets/andes_pagar_y_cobrar_tarjeta_de_credito_24.imageset/andes_pagar_y_cobrar_tarjeta_de_credito_24.png
Labels: Icons

#50 fix textfield multiline
  LibraryComponents/Classes/AndesTextField/AndesTextFieldDelegate.swift
  LibraryComponents/Classes/AndesTextField/View/AndesTextFieldDefaultView.xib
  LibraryComponents/Classes/AndesTextField/View/TextArea/AndesTextAreaView.xib
Labels: bug

#47 Badge IB props
  Example/AndesUI/Badges/Views/BadgeViewController.xib
  LibraryComponents/Classes/AndesBadge/AndesBadge.swift
Labels: enhancement

#53 Change from setters to properties [Message, Button], Adds @obj/@IBInspectable support
  CHANGELOG.md
  Example/AndesUI/Badges/Views/BadgeViewController.swift
  Example/AndesUI/Buttons/Views/ButtonsViewController.swift
  Example/AndesUI/Buttons/Views/ButtonsViewController.xib
  Example/AndesUI/Home/Views/HomeViewController.swift
  Example/AndesUI/Home/Views/HomeViewController.xib
  Example/AndesUI/Messages/Views/MessageViewController.swift
  Example/AndesUI/TextFields/Views/TextAreaViewController.swift
  Example/AndesUI/TextFields/Views/TextAreaViewController.xib
  Example/AndesUI/TextFields/Views/TextFieldViewController.swift
  Example/Tests/AndesButtonTests.swift
  Example/Tests/AndesMessageTests.swift
  LibraryComponents/Classes/AndesButton/AndesButton.swift
  LibraryComponents/Classes/AndesMessage/AndesMessage.swift
  LibraryComponents/Classes/AndesMessage/View/WithActions/AndesMessageWithActionsView.swift
  LibraryComponents/Classes/AndesTextField/State/AndesTextFieldStateReadonly.swift
Labels: BREAKING CHANGE, WIP
